// Centrální místo pro DOM selektory — když se v aplikaci přejmenují data-* atributy,
// změna je tady jen na jednom místě.

export const SEL = {
  canvas: '#canvas',
  viewport: '#viewport',
  map: '#map',
  labels: '#labels',
  hits: '#hits',
  nav: '#nav',
  navTabs: '#nav-tabs',
  homeBtn: '[data-home-btn]',
  homeDropdown: '#nav-dropdown',
  sourceBtn: '[data-source-btn]',
  sourceMenu: '[data-source-menu]',
  emptyState: '#empty-state',
  badge: '#badge[data-badge]',
  badgeTipBtn: '[data-badge-tip]',
  tipDialog: '[data-tip-dialog]',
  tipQr: '[data-tip-qr]',
  tipAccount: '[data-tip-account]',
  tipCopyBtn: '[data-tip-copy]',
  tipCloseBtn: '[data-tip-close]',
  panel: '.panel',
  panelHead: '[data-panel-head]',
  panelBody: '[data-panel-body]',
  panelClose: '[data-panel-close]',
  panelMax: '[data-panel-max]',
  panelPlay: '[data-panel-play]',
  vimMount: '[data-vim-mount]',
  hit: '.hit',
  label: '.labels [data-node-path]',
};
